name: sleep_enforcer_env
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Conda Packages ---
  - python==3.12
  - pillow
  - pystray
  - pyinstaller
  
  # --- Pip-Only Packages ---
  - pip:
    # - <some-package-conda-doesnt-have>