name: sleep_enforcer_windows_env
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Conda Packages ---
  - python==3.12
  - pillow
  - pip
  
  # --- Pip-Only Packages ---
  - pip:
    - pystray
    - pyinstaller
    # - <some-package-conda-doesnt-have>